[refer #991] Add /transactions/poolhist request to obtain mempool fee…
ergoplatform/ergo pull request #1175
Opened 2020-08-19 14:06 UTC by knizhnik

… histogram

2020-09-15 11:35 UTC, greenhat requested changes
Looking good, but:
1. I did not understand what is a "bean". Maybe you meant "bin"?
2. I did not find tests for added features.

2020-09-15 16:05 UTC, knizhnik commented
It is not quite clear how to write tests for the functions which behavior depends on system time. Certainly I can put some transactions in mempool, then take them with same delay, but in any case final result will be non determinstic and it is hard to find some reasonable bounds.

2020-09-15 19:49 UTC, kushti commented
> It is not quite clear how to write tests for the functions which behavior depends on system time. Certainly I can put some transactions in mempool, then take them with same delay, but in any case final result will be non determinstic and it is hard to find some reasonable bounds.

How's about to change a bit MemPoolStatistics:

def add(wtx : WeightedTxId) : Unit = add(wtx, System.currentTimeMillis())

private[mempool] add add(wtx : WeightedTxId, time: Long) = {
...
}

Then your test (located in package org.ergoplatform.nodeView.mempool ) can work with the private method and you can have precise control over testing data

2020-09-16 07:44 UTC, knizhnik commented
Current system time is used not only in add() method, but also in getExpectedWaitTime.
Actually time is not the main problem - I can add one second sleeps and roun d result to integer number of seconds.
Th main problem is that measurement precision (histogram bin and eexpected wait time) are minute. It seems to be too large for regression test.

2020-09-17 21:28 UTC, kushti commented
> Current system time is used not only in add() method, but also in getExpectedWaitTime.
> Actually time is not the main problem - I can add one second sleeps and roun d result to integer number of seconds.
> Th main problem is that measurement precision (histogram bin and eexpected wait time) are minute. It seems to be too large for regression test.


Why not to provide fake clocks to getExpectedWaitTime as well ?

2020-09-21 10:26 UTC, knizhnik commented
> > Current system time is used not only in add() method, but also in getExpectedWaitTime.
> > Actually time is not the main problem - I can add one second sleeps and roun d result to integer number of seconds.
> > Th main problem is that measurement precision (histogram bin and eexpected wait time) are minute. It seems to be too large for regression test.
> 
> Why not to provide fake clocks to getExpectedWaitTime as well ?

Because it still doesn't help to solve minute resolution problem.

2020-10-05 09:27 UTC, aslesarenko requested changes

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/http/api/TransactionsApiRoute.scala
> +  }
This method can be (and IMO should be) moved out of this route class (for example into some builder class). The time provider can then be abstracted and the algorithms is unit tested (including providing test vectors for regression, which is necessary for the public API)

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
> +  val measurementIntervalMsec = 60 * 1000 /* one hour */
Please add ScalaDoc for these public fields.

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
> +case class FeeHistogramBin(var nTxns: Int, var totalFee: Long)
please add ScalaDoc

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
> +case class MemPoolStatistics() {
Case classes without args is anti-pattern. Why not use `case object` then?
Also please add ScalaDoc.

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
> +  var snapTakenTxns : Long = 0          // amount of transaction at the moment of last snapshot
Please put these comments into ScalaDocs.

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
> +  // startMeasurement +            snapTime +      current time+
This should be put into ScalaDoc using PRE formatting. See ScalaDoc guide at scala-lang.org

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
> +    val now = System.currentTimeMillis()
The time provider can be introduced to abstract from time source and make this class unit-testable.

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
> +  }
Can be moved out to a histogram builder and then unit-tested independently of this mempool.

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
> +  }
Can be moved out to a histogram builder and then unit-tested independently of this mempool, in particular using mock time provider.

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
> +class ErgoMemPool private[mempool](pool: OrderedTxPool, stats : MemPoolStatistics)(implicit settings: ErgoSettings)
Please augment ScalaDoc with missing description of constructor parameters.

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
>    def process(tx: ErgoTransaction, state: ErgoState[_]): (ErgoMemPool, ProcessingOutcome) = {
Please add ScalaDoc for this public method.

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/OrderedTxPool.scala
> +    })
Public method, please add ScalaDoc.

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/OrderedTxPool.scala
> +  case class WeightedTxId(id: ModifierId, weight: Long, feePerKb: Long, created: Long) {
Please add ScalaDoc

2020-10-05 09:27 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/nodeView/mempool/OrderedTxPool.scala
> +    WeightedTxId(tx.id, feePerKb, feePerKb, System.currentTimeMillis())
The time source can be abstacted using time provider, then the `OrderedTxPool.put` method can be unit-tested (where this method is used).

2020-12-29 11:12 UTC, merged