V4.0.0 activation rules
ergoplatform/ergo pull request #1183
Opened 2020-09-10 21:32 UTC by kushti

2020-12-23 11:09 UTC, aslesarenko requested changes

2020-12-30 09:39 UTC, kushti commented on src/main/resources/mainnet.conf
> +    # Difficulty for Autolykos version 2 activation (corresponding
fixed

2021-01-05 10:45 UTC, kushti commented on src/main/scala/org/ergoplatform/settings/Parameters.scala
> +      require(table(BlockVersion) == 1, "Protocol version is not 1 on the hard-fork")
made a comment

2021-01-05 17:07 UTC, aslesarenko approved these changes
LGTM, but please address comments

2021-01-05 19:24 UTC, kushti commented on src/main/scala/org/ergoplatform/mining/AutolykosSolution.scala
> +    w.putBytes(obj.n)
done

2021-01-05 19:24 UTC, kushti commented on src/main/scala/org/ergoplatform/mining/AutolykosSolution.scala
> +  val v2Serializer = new AutolykosV2SolutionSerializer
done

2021-01-05 19:24 UTC, kushti commented on src/main/scala/org/ergoplatform/mining/AutolykosSolution.scala
> +  def serialize(h: Header, w: Writer): Unit = {
done

2021-01-05 19:27 UTC, kushti commented on src/main/scala/org/ergoplatform/modifiers/history/PoPowAlgos.scala
> +    * Computes max level (μ) of the given [[Header]], such that μ = log(T) − log(id(B))
fixed

2021-01-05 19:28 UTC, merged