CollectedBoxes refactored
ergoplatform/ergo pull request #1426
Opened 2021-08-11 14:23 UTC by semyonoskin

ChangeBoxes structure replaced with single value

2021-08-12 16:40 UTC, oskin1 commented on ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/DefaultBoxSelector.scala
> +        case None => Left(NoSuchTokensError(
Found assets `foundBoxAssets` not necessarily should all be in target. So we should put them into a change box, rather than fail.

2021-08-12 16:40 UTC, oskin1 commented on ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/DefaultBoxSelector.scala
> +        case Some(value) => acc.map(_.updated(id, amount - value))
It's better to rename `value` to more meaningful `targetAmount`.

2021-08-12 16:40 UTC, oskin1 commented on ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/DefaultBoxSelector.scala
> +          Left(NotEnoughTokensError(s"Not enough tokens to create change box", foundBoxAssets.toMap))
The text should be just `Not enough tokens`. I'm not sure though whether this check if the responsibility of this method.

2021-08-12 16:40 UTC, oskin1 commented on ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/DefaultBoxSelector.scala
> +        else if (!tMap.forall { case (_, amount) => amount >= 0 })
```suggestion
        else if (tMap.exists { case (_, amount) => amount < 0 })
```
should be slightly more efficient

2021-08-13 16:59 UTC, oskin1 approved these changes

2021-09-01 10:54 UTC, kushti requested changes

2021-09-01 10:54 UTC, kushti commented on ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/DefaultBoxSelector.scala
> +        if (changeBalance < 0)
You need to check also that storage rent requirements met (you can copy "changeBoxesAssets.size * MinBoxValue > changeBalance" check from previous version for that)

2021-09-01 10:54 UTC, kushti commented on ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/DefaultBoxSelector.scala
> +        else Right(Some(ErgoBoxAssetsHolder(changeBalance, tMap)))
To be sure, check for MaxTokens also

2021-09-18 20:14 UTC, kushti commented
Due to #1440 it seems we need to have multiple change outputs in some cases

2021-09-18 20:14 UTC, closed without merging