5.0 testnet
ergoplatform/ergo pull request #1751
Opened 2022-06-24 14:39 UTC by kushti

2022-10-17 08:34 UTC, aslesarenko requested changes

2022-10-17 14:21 UTC, kushti commented on src/main/resources/testnet.conf
> +    magicBytes = [2, 0, 2, 3]
There is no schema, a new network just need to have new magic bytes. So I do not quite understand what are you asking to document

2022-10-17 14:24 UTC, kushti commented
@aslesarenko comments addressed, please make another pass

2022-10-18 07:41 UTC, aslesarenko commented on src/main/resources/testnet.conf
> +    magicBytes = [2, 0, 2, 3]
I think you can put this comment to the code "There is no schema, a new network just need to have new magic bytes."

2022-10-18 07:44 UTC, aslesarenko commented on src/test/scala/org/ergoplatform/modifiers/mempool/ErgoTransactionSpec.scala
> +  }
Well, but the concern still the same.

2022-10-18 07:44 UTC, aslesarenko approved these changes
LGTM, but see unresolved conversations.

2022-10-18 14:39 UTC, pragmaxim approved these changes

2022-10-21 13:05 UTC, kushti commented on src/main/resources/testnet.conf
> +    magicBytes = [2, 0, 2, 3]
The comment is already specifying the goal of the bytes, i.e. distinguishing one network from another. If other properties are not stated, they are not needed.

2022-10-21 13:05 UTC, merged