Candidate for 4.0.35
ergoplatform/ergo pull request #1766
Opened 2022-07-05 15:59 UTC by kushti

2022-07-18 12:00 UTC, aslesarenko requested changes

2022-07-20 12:28 UTC, pragmaxim commented on src/main/scala/scorex/core/network/peer/RestApiUrlPeerFeature.scala
> +    val fas = r.getUByte()
Addressed in https://github.com/ergoplatform/ergo/pull/1766/commits/5f6ea837c8e50ab0eb561219636720b920f94fd0 ... let's write it as unsinged byte and increase the max to 255 ... My apologies, this was a good catch, thank you

2022-07-20 12:56 UTC, kushti commented on src/main/scala/org/ergoplatform/modifiers/BlockSection.scala
> -  */
This is now a ScalaDoc for `NonHeaderBlockSection`, made a new ScalaDoc for BlockSection

2022-07-20 12:58 UTC, kushti commented on src/main/scala/org/ergoplatform/settings/PeerFeatureIds.scala
> +    * See `LocalAddressPeerFeature`
It does

2022-07-20 12:59 UTC, kushti commented on src/main/scala/org/ergoplatform/settings/PeerFeatureIds.scala
> +    * See `LocalAddressPeerFeature`
Fixed by @pragmaxim

2022-07-20 13:00 UTC, kushti commented on src/main/scala/scorex/core/network/message/BasicMessagesRepo.scala
> +  private val maxHandshakeSize = 8096
Not sure it is needed actually, no any uses around

2022-07-21 10:53 UTC, pragmaxim approved these changes

2022-07-22 15:38 UTC, aslesarenko approved these changes

2022-07-25 10:38 UTC, merged