Candidate for 5.0.7
ergoplatform/ergo pull request #1942
Opened 2023-01-25 12:03 UTC by kushti

2023-02-09 18:16 UTC, aslesarenko requested changes

2023-02-09 21:47 UTC, jellymlg commented on src/main/resources/api/openapi.yaml
> +        - spendingHeight
They are null when the box is unspent, just like in the explorer.

2023-02-09 22:25 UTC, jellymlg commented on avldb/src/main/scala/scorex/db/LDBKVStore.scala
> +      cfor(0)(_ < toRemove.length, _ + 1) { i => batch.delete(toRemove(i))}
done

2023-02-09 22:25 UTC, jellymlg commented on src/main/resources/api/openapi.yaml
> +          description: The global index of the box
Copied explorer description for accuracy

2023-02-09 22:25 UTC, jellymlg commented on src/main/resources/api/openapi.yaml
> +          description: index of the box globally
It should have been transaction, done

2023-02-09 22:25 UTC, jellymlg commented on src/main/resources/api/openapi.yaml
> +                    description: Total count of transactions
It should be retrieved, done

2023-02-09 22:26 UTC, jellymlg commented on src/main/resources/api/openapi.yaml
> +                    description: Total number of boxes
done

2023-02-09 22:26 UTC, jellymlg commented on src/main/resources/api/openapi.yaml
> +                    description: Total number of boxes
done

2023-02-09 22:26 UTC, jellymlg commented on src/main/resources/api/openapi.yaml
> +                $ref: '#/components/schemas/IndexedErgoBox'
yes, fixed

2023-02-09 22:26 UTC, jellymlg commented on src/main/resources/application.conf
> +      extraCacheSize = 500
There is only an enable flag and a cache size, so I don't think its worth grouping together.

2023-02-09 22:26 UTC, jellymlg commented on src/main/scala/org/ergoplatform/http/api/ApiCodecs.scala
> +  implicit val ergoAddressEncoder: ErgoAddressEncoder = null
It gets overridden and is only used for getting the address of a box from its ergotree

2023-02-09 22:26 UTC, jellymlg commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  private val MaxItems = 16384
Copied from BlocksApiRoute MaxHeaders

2023-02-09 22:26 UTC, jellymlg commented on src/main/scala/org/ergoplatform/local/ErgoStatsCollector.scala
> +        "isExplorer" -> ni.extraIndex.asJson,
Because thats the name of the functionality the indexer ultimately provides

2023-02-09 22:56 UTC, aslesarenko commented on src/main/resources/api/openapi.yaml
> +        - spendingHeight
In this case they better be Option, and there is not need to have the `spent` flag. 
@kushti what do you think about having `null` in the properties?

2023-02-09 22:59 UTC, aslesarenko commented on src/main/resources/api/openapi.yaml
> +          description: The global index of the box
I think this `global` terminology misleading. Why not describe where the index values come from and how they are created instead on `global` which is mostly meaningless.

2023-02-09 22:59 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  private val MaxItems = 16384
Ok, leave the comment in code then.

2023-02-09 23:03 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/local/ErgoStatsCollector.scala
> +        "isExplorer" -> ni.extraIndex.asJson,
Why not use `isExplorer` instead of extraIndex? Actually I think consistency is more important then any particular name.

2023-02-13 22:11 UTC, kushti commented on src/main/resources/api/openapi.yaml
> +        - spendingHeight
@aslesarenko both options are used in openapi.yaml

2023-02-13 22:13 UTC, kushti commented on src/main/scala/org/ergoplatform/local/ErgoStatsCollector.scala
> +    lastIncomingMessageTime = System.currentTimeMillis(),
There is no networkTime() , rationale behind removing NTP is described in https://github.com/ergoplatform/ergo/pull/1943 , I see no value in providing changelog in the code (aside of consensus-critical code and networking messages)

2023-02-13 22:16 UTC, kushti commented on src/main/scala/org/ergoplatform/network/ErgoSyncTracker.scala
> +          (currentTime() - status.lastSyncSentTime.getOrElse(0L)).millis >= MinSyncInterval
wdym? it is called in different methods

2023-02-13 22:25 UTC, kushti commented on src/main/scala/org/ergoplatform/network/ErgoNodeViewSynchronizer.scala
> +    case class Rollback(branchPoint: ModifierId) extends NodeViewHolderEvent
done

2023-02-13 23:00 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/network/ErgoSyncTracker.scala
> +          (currentTime() - status.lastSyncSentTime.getOrElse(0L)).millis >= MinSyncInterval
currentTime() is called once for each item in nonOutdated

2023-02-14 12:26 UTC, kushti commented on src/main/scala/org/ergoplatform/local/ErgoStatsCollector.scala
> +        "isExplorer" -> ni.extraIndex.asJson,
@aslesarenko the name for the field was discussed in the discord chat

2023-02-14 12:34 UTC, kushti commented on src/main/scala/org/ergoplatform/network/ErgoSyncTracker.scala
> +          (currentTime() - status.lastSyncSentTime.getOrElse(0L)).millis >= MinSyncInterval
fixed

2023-02-14 13:14 UTC, aslesarenko approved these changes

2023-02-16 12:52 UTC, merged