ChatGPT Plugin for Ergo Node API
ergoplatform/ergo pull request #2008
Opened 2023-06-07 14:09 UTC by aslesarenko

In this PR:
- [x] A simplified OpenAPI  (`openapi-ai.yaml` file) added with a small subset of API endpoint specifications (see [article on hackernoon]()  for discussion of why a separate specification is necessary)
- [x] plugin manifest configuration is added to `.well-known/ai-plugin.json`
- [x] special Routes implemented which are requested by ChatGPT UI:
    - [`http://localhost:9053](http://localhost:9053)/.well-known/ai-plugin.json` - to get manifest
    - [`http://localhost:9053](http://localhost:9053)/openapi.yaml` - to get specification of API endpoints
- [x] Additional Routes implemented for new `get` endpoints which was added in openapi-ai.yaml
- [x] Additional response headers configured for ErgoHttpService (CorsHandler used by Ergo node)

2023-06-19 11:01 UTC, kushti requested changes

2023-06-19 11:01 UTC, kushti commented on src/main/resources/api/openapi.yaml
> +          description: Height of a block to retrive header ids
retrive => retrieve

2023-06-21 11:15 UTC, aslesarenko commented on src/main/resources/.well-known/ai-plugin.json
> +  "contact_email": "legal@example.com",
The [logo url](https://cryptologos.cc/logos/ergo-erg-logo.png) is valid.
And I changed the email to team@ergoplatform.org

2023-06-21 11:32 UTC, aslesarenko commented on src/main/resources/.well-known/ai-plugin.json
> +    "url": "http://localhost:9052/openapi.yaml",
fixed

2023-06-21 11:34 UTC, aslesarenko commented on src/main/resources/api/openapi.yaml
> +  - url: http://localhost:9052
fixed

2023-06-21 11:35 UTC, aslesarenko commented on src/main/resources/api/openapi.yaml
> +          description: Size of ErgoTransacton in bytes
fixed

2023-06-21 11:38 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  private def getTxsByAddressR_get: Route = (pathPrefix("transaction" / "byAddress") & get & addressPass & paging) { (address, offset, limit) =>
here `_get` part is somewhat special suffix, and `_` make it separate form the name. 
Please suggest the name, I'm ok with anything you suggest.

2023-06-21 11:38 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  private def getBoxesByAddressR_get: Route = (pathPrefix("box" / "byAddress") & get & addressPass & paging) { (address, offset, limit) =>
please suggest a name

2023-06-21 11:42 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  val addressPass: Directive1[ErgoAddress] = pathPrefix(Segment).flatMap(handleErgoAddress)
fixed

2023-06-21 11:45 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  private def getAddressBalanceTotalR_v2: Route =
Fixed, changed to `_get` suffix to be consistent with other names. If you suggest another name, will change this as well. See my reply above.

2023-06-21 11:46 UTC, aslesarenko commented on src/main/resources/api/openapi.yaml
> +          description: Height of a block to retrive header ids
fixed

2023-06-26 13:30 UTC, kushti commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  private def getBoxesByAddressR_get: Route = (pathPrefix("box" / "byAddress") & get & addressPass & paging) { (address, offset, limit) =>
same as above

2023-06-26 15:09 UTC, aslesarenko commented on src/main/resources/api/openapi-ai.yaml
> +  version: "5.0.10"
done

2023-06-26 15:10 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  private def getTxsByAddressR_get: Route = (pathPrefix("transaction" / "byAddress") & get & addressPass & paging) { (address, offset, limit) =>
done

2023-06-26 15:17 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  private def getBoxesByAddressR_get: Route = (pathPrefix("box" / "byAddress") & get & addressPass & paging) { (address, offset, limit) =>
done

2023-06-26 15:19 UTC, aslesarenko commented on src/main/scala/org/ergoplatform/http/api/BlockchainApiRoute.scala
> +  private def getAddressBalanceTotalR_v2: Route =
changed suffix to GetRoute

2023-08-22 10:36 UTC, kushti approved these changes

2023-08-22 10:36 UTC, merged