Flag that a peer was bootstrapped via UTXO set snapshot
ergoplatform/ergo pull request #2022
Opened 2023-08-14 20:42 UTC by kushti

2023-08-15 16:06 UTC, aslesarenko requested changes

2023-08-16 12:07 UTC, kushti commented on src/main/scala/org/ergoplatform/network/ModePeerFeature.scala
> +  val UTXOSetBootstrapped = -2
fixed

2023-08-16 12:08 UTC, kushti commented on src/main/scala/org/ergoplatform/network/ModePeerFeature.scala
> +  * @param nipopowBootstrapped - whether the peer has bootstrapped via Nipopows
fixed

2023-08-16 12:08 UTC, kushti commented on src/main/scala/org/ergoplatform/network/ModePeerFeature.scala
>    * @param blocksToKeep - how many last full blocks the peer is storing
fixed

2023-08-16 12:20 UTC, kushti commented
@aslesarenko comments addressed, please make another pass

2023-08-17 10:49 UTC, merged